project_id = "bduzroexsjwkiqcwzjha"

[functions.validate-receipt]
verify_jwt = false

[functions.extract-receipt-data]
verify_jwt = false

[functions.telegram-ban-bot]
verify_jwt = false

[functions.bulk-resend-notifications]
verify_jwt = false

[functions.generate-thank-you]
verify_jwt = false

[functions.send-coins-notification]
verify_jwt = false

[functions.send-coins-status-notification]
verify_jwt = false

[functions.send-webhook-notification]
verify_jwt = false

[functions.webhook-lookup]
verify_jwt = false
